class CityTR {
  const CityTR({required this.code, required this.name});

  final String code;
  final String name;
}

const List<CityTR> kCitiesTR = [
  CityTR(code: '01', name: 'Adana'),
  CityTR(code: '02', name: 'Adıyaman'),
  CityTR(code: '03', name: 'Afyonkarahisar'),
  CityTR(code: '04', name: 'Ağrı'),
  CityTR(code: '68', name: 'Aksaray'),
  CityTR(code: '05', name: 'Amasya'),
  CityTR(code: '06', name: 'Ankara'),
  CityTR(code: '07', name: 'Antalya'),
  CityTR(code: '75', name: 'Ardahan'),
  CityTR(code: '08', name: 'Artvin'),
  CityTR(code: '09', name: 'Aydın'),
  CityTR(code: '10', name: 'Balıkesir'),
  CityTR(code: '74', name: 'Bartın'),
  CityTR(code: '72', name: 'Batman'),
  CityTR(code: '69', name: 'Bayburt'),
  CityTR(code: '11', name: 'Bilecik'),
  CityTR(code: '12', name: 'Bingöl'),
  CityTR(code: '13', name: 'Bitlis'),
  CityTR(code: '14', name: 'Bolu'),
  CityTR(code: '15', name: 'Burdur'),
  CityTR(code: '16', name: 'Bursa'),
  CityTR(code: '17', name: 'Çanakkale'),
  CityTR(code: '18', name: 'Çankırı'),
  CityTR(code: '19', name: 'Çorum'),
  CityTR(code: '20', name: 'Denizli'),
  CityTR(code: '21', name: 'Diyarbakır'),
  CityTR(code: '81', name: 'Düzce'),
  CityTR(code: '22', name: 'Edirne'),
  CityTR(code: '23', name: 'Elazığ'),
  CityTR(code: '24', name: 'Erzincan'),
  CityTR(code: '25', name: 'Erzurum'),
  CityTR(code: '26', name: 'Eskişehir'),
  CityTR(code: '27', name: 'Gaziantep'),
  CityTR(code: '28', name: 'Giresun'),
  CityTR(code: '29', name: 'Gümüşhane'),
  CityTR(code: '30', name: 'Hakkâri'),
  CityTR(code: '31', name: 'Hatay'),
  CityTR(code: '76', name: 'Iğdır'),
  CityTR(code: '32', name: 'Isparta'),
  CityTR(code: '34', name: 'İstanbul'),
  CityTR(code: '35', name: 'İzmir'),
  CityTR(code: '46', name: 'Kahramanmaraş'),
  CityTR(code: '78', name: 'Karabük'),
  CityTR(code: '70', name: 'Karaman'),
  CityTR(code: '36', name: 'Kars'),
  CityTR(code: '37', name: 'Kastamonu'),
  CityTR(code: '38', name: 'Kayseri'),
  CityTR(code: '79', name: 'Kilis'),
  CityTR(code: '71', name: 'Kırıkkale'),
  CityTR(code: '39', name: 'Kırklareli'),
  CityTR(code: '40', name: 'Kırşehir'),
  CityTR(code: '41', name: 'Kocaeli'),
  CityTR(code: '42', name: 'Konya'),
  CityTR(code: '43', name: 'Kütahya'),
  CityTR(code: '44', name: 'Malatya'),
  CityTR(code: '45', name: 'Manisa'),
  CityTR(code: '47', name: 'Mardin'),
  CityTR(code: '33', name: 'Mersin'),
  CityTR(code: '48', name: 'Muğla'),
  CityTR(code: '49', name: 'Muş'),
  CityTR(code: '50', name: 'Nevşehir'),
  CityTR(code: '51', name: 'Niğde'),
  CityTR(code: '52', name: 'Ordu'),
  CityTR(code: '80', name: 'Osmaniye'),
  CityTR(code: '53', name: 'Rize'),
  CityTR(code: '54', name: 'Sakarya'),
  CityTR(code: '55', name: 'Samsun'),
  CityTR(code: '63', name: 'Şanlıurfa'),
  CityTR(code: '56', name: 'Siirt'),
  CityTR(code: '57', name: 'Sinop'),
  CityTR(code: '73', name: 'Şırnak'),
  CityTR(code: '58', name: 'Sivas'),
  CityTR(code: '59', name: 'Tekirdağ'),
  CityTR(code: '60', name: 'Tokat'),
  CityTR(code: '61', name: 'Trabzon'),
  CityTR(code: '62', name: 'Tunceli'),
  CityTR(code: '64', name: 'Uşak'),
  CityTR(code: '65', name: 'Van'),
  CityTR(code: '77', name: 'Yalova'),
  CityTR(code: '66', name: 'Yozgat'),
  CityTR(code: '67', name: 'Zonguldak'),
];
